sonar.projectKey=rahulvaidyasdlc_flask-jenkins
sonar.projectName=flask-student-demo
sonar.organization=rahulvaidyasdlc
sonar.sources=app.py,templates/
sonar.tests=tests/
sonar.python.version=3
# Path to the coverage report generated in the Jenkins 'Test' stage
sonar.python.coverage.reportPaths=coverage.xml
